import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import './../node_modules/bootstrap/dist/css/bootstrap.min.css';
import App from './App';

import SimpleStateComponent from './components/simplestatecomponent/simplestatecomponent';


import reportWebVitals from './reportWebVitals';
import DepartmentCompoent from './components/departmentcomponent/deptcomponent';
import DepartmentRESTCompoent from './components/departmentcomponentrest/deptrestcomponent';
// Read the HTMl element from 'index.html' which is
// present in the 'public' folder

const root = ReactDOM.createRoot(document.getElementById('root'));
// The 'App' component is mounterd and rendered in the root

/* Define a property */

let message = 'Hello Mr. App';
root.render(
  <React.StrictMode>
    {/* the 'msg' is a 'props' type that will be dynamically generated by JSX 
    The 'msg' is passed to the App Compponent
    */}
    {/* <App msg={message}/> */}
    {/* <SimpleStateComponent/> */}
    {/* <DepartmentCompoent/> */}
    <DepartmentRESTCompoent/>
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
